language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: p7xWGohE7bPty94m8BARroKhV9uwjo/hkkGbGGtWM5CUwnpaJiMd596/+r55eTP1FfooS85yDzxVqdz8dttkC4G9DTfYyu1omveoRPZC+LbZsudTBFmEeh+1KJwUBHkBAquJu2JPQ9Q2ZOkprR/e4kQaPG95aeGVY01jyRhtQ9hgF7SxiEcD7SDxaSNSe+wd1R1qPjOe30ZIkTAwta/ro3WaT2WacTrOyNssdEBd6wJPBHXrk/vNrrl9Fsd/BiHlC9c0zximPlJ+xTkjgmjmlNA8PW7eX2Z5fWNuGEVdkAFKtOdXGi17SCwcKW/mELSO14D9An2TBLPlRu5DmnzaYudw1dERXaUp/5qN6lFYneVapSYaAW5y8EqEWuPImkZ4Oqd15/RCw6KycLAN8xSY2tE+FIYKO28X/NePQdvxOlJp3jstkurw/p49LrPIBWsB470wzMA+IZ+K8c1gvQab+Y+R9n7S4sBw27HbynboToOUfJ23GTFzn+e6INBsNkaGQELX2d+CjWtyyDOWKsmjZJLP+ynF/3ZX1Hg7bKeLuTicN6j2TEk66SsuwOM+w/NJ8iuIk/vWcaTKj0gcNexL3Trw1pS2ExO9RNB0vOcY8L3NNWplfxsD0dSK0na5RsIFUF6TL6uvz5yxoyZS+OKVkNsm5s96Ilog+bAR+jhbaFI=
  app: powerful-garden-47769
  on:
    repo: aamay001/reminder-app
