language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: DnajDzyHVNJIfhsm+juCn4F54gJLN39nPuv9LyZHYXVg/usCT8/DA1Wp3VWYq34+iUxQaVHdaFs08At4xHiEEHVRK8oKuukXNYVL7GH33qM5t97ngPJvON9ZzA0CrT1tsg6y41/5EX35hSnWvDhvevFdrm+UAr++xLREZ3hMOmoEl78ZIt0HDj15Kpa2u0UOdUrpHrPWezb2sAM3spgdRydf5AxmsJD3HkGkA8O07nAUmSDsnJFoWOFWwVTl82LqjTXf+qwcgVSVUpYBOcNVNIXI5I5yBLKU8IR7bdOGhcSA71qmOxdh8ZQdMXsXxM08AeKa96/v7QD7rmTSULct8XPBdABrz1ndCi5MiV/q4liShdYm/ztF8EFfYpjmII+sEtPNjFlaOtSSkxsfN60AMJ2QzlFotuHwhCYUiwOP+pd6dg9pAgMU6uc+vocKjEiO8AExUZi7DoHhb29zaDWpKCiBQSLV+MIUKv/V/6azp/e76FYDjJ3fLTEHRL9a9tTeSiU3pUFgb7GTuVKxtoPLrX5vBm02KfQo2Ij7ZkSy4tH+pEEtJ8t5FUoC5nAu5Eu24uk/+NpIkfwAlVjNjfxqzAr4IQcKLJ2mF9y8GlRlQk/2NGRIg/5h+UWrB91YooagOl1dL979vtJn6BczCoLRWFX50hWz1exibeUsiSefpI4=
  app: tellmeondate
  on:
    repo: aamay001/reminder-app
